### PR TITLE
added support for ASUS AC68 with new product id

### PR DESCRIPTION
**Pull request by asbroad**
ASUS has released another version of the AC68 wireless usb card that uses a new product id

### CODE REVIEW

**Comment by MarcosCC** [comment]
Thanks, Alexander.

Unfortunately, I can't compile diederekdehass' fork in Debian Buster (testing) as I get these errors:

make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-1-amd64/build M=/usr/src/rtl8814AU  modules                                   
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-1-amd64'                                                                  
  CC [M]  /usr/src/rtl8814AU/core/rtw_cmd.o                                                                                          
In file included from /usr/src/rtl8814AU/include/drv_types.h:32:0,
                 from /usr/src/rtl8814AU/core/rtw_cmd.c:22:
/usr/src/rtl8814AU/include/osdep_service.h: In function ‘thread_enter’:
/usr/src/rtl8814AU/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/usr/src/rtl8814AU/include/osdep_service.h: In function ‘flush_signals_thread’:
/usr/src/rtl8814AU/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/usr/src/rtl8814AU/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
/usr/src/linux-headers-4.13.0-1-common/scripts/Makefile.build:307: recipe for target '/usr/src/rtl8814AU/core/rtw_cmd.o' failed
make[4]: *** [/usr/src/rtl8814AU/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.13.0-1-common/Makefile:1529: recipe for target '_module_/usr/src/rtl8814AU' failed
make[3]: *** [_module_/usr/src/rtl8814AU] Error 2
Makefile:145: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-1-amd64'
Makefile:1699: recipe for target 'modules' failed
make: *** [modules] Error 2

Any chance in getting it for for example https://github.com/lkw16/rtl8814AU

Sorry, I am not a programmer.

Thank you!

Marcos

**Comment by asbroad** [comment]
Hi Marcos,

Ah I see.  From your logs, it appears that I am unfortunately using a
different Linux Distro (Ubuntu) and kernel then you are, so I'm not sure
that I'll be able to help.  

Good luck figuring it out!

(for others viewing this thread, this comment is in response to Marco's comment on the issue page)

Best,
Alex

**Comment by enanablancaynumeros** [comment]
I just bought a new ASUS AC68 with a new product id `0x1853`, so I just added a new line replicating the line [209](https://github.com/diederikdehaas/rtl8814AU/blob/driver-4.3.21/os_dep/linux/usb_intf.c#L209) and it just worked with:

```
make && sudo make install && sudo reboot
```

I am running Ubuntu 16.04 `(4.4.0-109-generic)`.
Not sure if it worths a PR as it looks like we could keep adding more and more product ids.

**Comment by ssube** [comment]
fwiw, I also have an ASUS AC-68 with the `0x1853` ID, and it seems to be this same chipset. A [similar driver](https://github.com/nazar-pc/RTL8814AU) has been working well (`4.13.0-38-generic`).

**Comment by diederikdehaas** [comment]
Included it in the new driver version/branch: [driver-5.8.5.1](https://github.com/diederikdehaas/rtl8814AU/tree/driver-5.8.5.1)

Thanks.

**Pull request closed without merging**
